// Code generated by "stringer -type=Network"; DO NOT EDIT.

package forker

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TCP4-1]
	_ = x[TCP6-2]
	_ = x[UDP-3]
	_ = x[UDP4-4]
	_ = x[UDP6-5]
}

const _Network_name = "tcp4tcp6udpudp4udp6"

var _Network_index = [...]uint8{0, 4, 8, 11, 15, 19}

func (i Network) String() string {
	i -= 1
	if i < 0 || i >= Network(len(_Network_index)-1) {
		return "Network(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Network_name[_Network_index[i]:_Network_index[i+1]]
}
